### DISCUSSION TITLE
GitHub action which focuses on Accessibility

### DISCUSSION THREAD

**Discussion by Pradumnasaraf** [AccessibleForAll/Support#2] [Ideas]
List of GitHub action which focuses on Accessibility,

**Comment by EmmaDawsonDev** [comment]
This is a great idea! Thanks for adding it.

**Reply by MarkusEicher** [reply]
Hi Pradumna

I also think this would be great. If we can help people automate some A11Y tasks with GitHub Actions that would be very helpful.

**Reply by Pradumnasaraf** [reply]
Great point, Markus!

**Reply by luck18210** [reply]
Good.

**Comment by jmohan57** [comment]
Nice

**Comment by plzbugmenot** [comment]
You can use this code.

```
name: Accessibility Check

on: [push, pull_request]

jobs:
  accessibility:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install axe-core

      - name: Run accessibility tests
        run: |
          node -e "const axe = require('axe-core'); axe.run('http://localhost:3000', (err, results) => { if (err) throw err; console.log(results); });"

```
